### ISSUE TITLE
可以提供金蝶云的SDK包吗？

### ISSUE THREAD

**Issue by JacksonChen-czc** [lmmarisej/DDD-smartrm-monolith-study#1]
我拉取了代码后，发现需要本地jar包k3cloud-webapi-sdk.7.6.x.jar，请问可以提供百度云下载吗？

**Comment by lmmarisej** [comment]
> 我拉取了代码后，发现需要本地jar包k3cloud-webapi-sdk.7.6.x.jar，请问可以提供百度云下载吗？

可以  我回去找找

**Comment by JacksonChen-czc** [comment]
> > 我拉取了代码后，发现需要本地jar包k3cloud-webapi-sdk.7.6.x.jar，请问可以提供百度云下载吗？
> 
> 可以 我回去找找

先谢谢了。可以在项目代码中加上数据库脚本吗？

**Comment by JacksonChen-czc** [comment]
牛啊，整套资料都给了，谢谢。
我找到的课程只有视频，没有配套资料，实在太感谢。
